name: olfanalyzer

networks:
  olfanalyzer:
    driver: bridge

volumes:
  storage_data:
  collector_hotdir:
  collector_outputs:
  postgres_data:

services:
  olfanalyzer:
    container_name: olfanalyzer
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
      args:
        ARG_UID: ${UID:-1000}
        ARG_GID: ${GID:-1000}
    cap_add:
      - SYS_ADMIN
    volumes:
      - "./.env:/app/server/.env"
      - "storage_data:/app/server/storage"
      - "collector_hotdir:/app/collector/hotdir"
      - "collector_outputs:/app/collector/outputs"
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - "3001:3001"
    env_file:
      - .env
    networks:
      - olfanalyzer
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres

  postgres:
      image: postgres:latest
      container_name: postgres
      environment:
        POSTGRES_USER: olfz-user
        POSTGRES_PASSWORD: 9685redJHftB7HJht7trr
        POSTGRES_DB: olfanalyzer_db
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      networks:
        - olfanalyzer
